### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BadMachine** [yuanyuanli85/Fast_Human_Pose_Estimation_Pytorch#20]
## Question
Can you provide info about license?
Is it free for commercial purpose? and redis under https://github.com/ilovepose/fast-human-pose-estimation.pytorch/blob/master/LICENSE this license?

**Comment by yuanyuanli85** [comment]
Done. have added the license file. Apach-2.0

**Comment by BadMachine** [comment]
@yuanyuanli85 Thank you!
