### ISSUE TITLE
python example/mpii_kd.py -a hg --stacks 2 --blocks 1 --checkpoint checkpoint/hg_s2_b1_mobile/ mobile=True --teacher_stack 8 --teacher_checkpoint 

### ISSUE THREAD

**Issue by Nanawu123** [yuanyuanli85/Fast_Human_Pose_Estimation_Pytorch#23]
python example/mpii_kd.py -a hg --stacks 2 --blocks 1 --checkpoint checkpoint/hg_s2_b1_mobile/ mobile=True --teacher_stack 8 --teacher_checkpoint 
Hello, does stack 8 mean that the teacher network is 8 hourglasses? Does stacks 2 mean that the student network consists of two hourglass networks?
checkpoint/hg_s8_b1/model_best.pth.tar 
![image](https://user-images.githubusercontent.com/73815521/97839769-cddcf880-1d1d-11eb-89c9-92498f656871.png)

**Comment by yuanyuanli85** [comment]
yes, you are right.
