### ISSUE TITLE
有个问题，试了下其他类型图片，效果并不好，是否只适用于mpii数据集上图片？

### ISSUE THREAD

**Issue by DragonAndSky** [yuanyuanli85/Fast_Human_Pose_Estimation_Pytorch#6]
![test_result](https://user-images.githubusercontent.com/21075743/52923441-cebfd200-3362-11e9-92fb-4b0272d808cf.jpg)

**Comment by yuanyuanli85** [comment]
This network is trained for single person pose estimation. If your input is a image with multiple persons, the detection would be bad.

**Comment by DragonAndSky** [comment]
I understand. The Image need target detection first, thanks
