### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by ZhaoliangHe** [yuanyuanli85/Fast_Human_Pose_Estimation_Pytorch#7]
I am getting the above error (mentioned in title) when i run the code:python tools/mpii_demo.py -a hg -s 2 -b 1 --mobile True --checkpoint checkpoint/mpii_hg_s2_b1_mobile_fpd/model_best.pth.tar --in_res 256 --device cuda .what should I do?

**Comment by yuanyuanli85** [comment]
@ZhaoliangHe  please check 13fa58a6ba4f9f89b0b559521d464685ecff8d2f for fix.  Just add one line code to push model to device.  `model = model.to(device)`
